{{- if and .Values.configs.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-configmap
  annotations:
  labels:
    app: {{ include "service.fullname" . }}
    release: {{ .Release.Name }}
data: 
  {{- range $key, $value := .Values.configs }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end -}}
