{{- if .Values.ingress.enabled -}}
{{- $fullName := include "service.fullname" . }}
{{- $httpPort := .Values.service.httpPort }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ include "service.fullname" . }}
    release: {{ .Release.Name }}
  name: {{ template "service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}       
      http:
        paths:
        - backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $httpPort }}
          path: /
          pathType: ImplementationSpecific      
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
