{{- if and .Values.secrets.enabled -}}
apiVersion: v1
kind: Secrets
metadata:
  name: {{ include "service.fullname" . }}-configmap
  annotations:
  labels:
    app: {{ include "service.fullname" . }}
    release: {{ .Release.Name }}
data:
  {{- range $key,$value := .Values.secrets.all }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end -}}

