{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "service.fullname" . }}
    release: {{ .Release.Name }}
{{- end }}
